export const imagesDetails = [
  {
    key: 1,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(1).jpg",
    price: "????",
    likes: 8,
  },
  {
    key: 2,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(2).jpg",
    price: "????",
    likes: 12,
  },
  {
    key: 3,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(3).png",
    price: "????",
    likes: 55,
  },
  {
    key: 4,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(4).png",
    price: "????",
    likes: 444,
  },
  {
    key: 5,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(5).png",
    price: "????",
    likes: 66,
  },
  {
    key: 6,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(6).png",
    price: "????",
    likes: 77,
  },
  {
    key: 7,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(7).png",
    price: "????",
    likes: 88,
  },
  {
    key: 8,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(8).png",
    price: "????",
    likes: 89,
  },
  {
    key: 9,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(9).png",
    price: "????",
    likes: 177,
  },
  {
    key: 10,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(10).png",
    price: "????",
    likes: 988,
  },
  {
    key: 11,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(11).png",
    price: "????",
    likes: 888,
  },
  {
    key: 12,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(12).png",
    price: "????",
    likes: 69,
  },
  {
    key: 13,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(13).png",
    price: "????",
    likes: 430,
  },
  {
    key: 14,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(14).png",
    price: "????",
    likes: 434,
  },
  {
    key: 15,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(15).png",
    price: "????",
    likes: 321,
  },
  {
    key: 16,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(16).png",
    price: "????",
    likes: 783,
  },
  {
    key: 17,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(17).png",
    price: "????",
    likes: 123,
  },
  {
    key: 18,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(18).png",
    price: "????",
    likes: 346,
  },
  {
    key: 19,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(19).png",
    price: "????",
    likes: 784,
  },
  {
    key: 20,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(20).png",
    price: "????",
    likes: 373,
  },
  {
    key: 21,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(21).png",
    price: "????",
    likes: 157,
  },
  //   {
  //     key: 22,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(22).png",
  //     price: "????",
  //     likes: 10,
  //   },
  //   {
  //     key: 23,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(23).png",
  //     price: "????",
  //     likes: 10,
  //   },
  //   {
  //     key: 24,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(24).png",
  //     price: "????",
  //     likes: 10,
  //   },
  //   {
  //     key: 25,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(25).png",
  //     price: "????",
  //     likes: 10,
  //   },
  //   {
  //     key: 26,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(26).png",
  //     price: "????",
  //     likes: 10,
  //   },
  //   {
  //     key: 27,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(27).jpg",
  //     price: "????",
  //     likes: 10,
  //   },
  //   {
  //     key: 28,
  //     name: "Pastel Peeps",
  //     imageSrc: "/scroll-images/scroll(28).jpg",
  //     price: "????",
  //     likes: 10,
  //   },

  {
    key: 1,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(1).jpg",
    price: "????",
    likes: 120,
  },
  {
    key: 2,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(2).jpg",
    price: "????",
    likes: 563,
  },
  {
    key: 3,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(3).png",
    price: "????",
    likes: 123,
  },
  {
    key: 4,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(4).png",
    price: "????",
    likes: 75,
  },
  {
    key: 5,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(5).png",
    price: "????",
    likes: 4578,
  },
  {
    key: 6,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(6).png",
    price: "????",
    likes: 345,
  },
  {
    key: 7,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(7).png",
    price: "????",
    likes: 234,
  },
  {
    key: 8,
    name: "Pastel Peeps",
    imageSrc: "/scroll-images/scroll(8).png",
    price: "????",
    likes: 67,
  },
];
